# Generated by Django 4.2.7 on 2025-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('REPAIR', 'Reparación/Avería'), ('NEW_SERVICE', 'Nuevo Servicio'), ('MAINTENANCE', 'Mantenimiento'), ('COMPLAINT', 'Queja/Reclamo'), ('INFORMATION', 'Solicitud de Información')], max_length=50, verbose_name='Tipo de Solicitud'),
        ),
    ]
