# Generated by Django 4.2.7 on 2025-09-27 17:12

import apps.requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], max_length=50, null=True, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='to_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], max_length=50, verbose_name='Nuevo Estado'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ticket_number',
            field=models.CharField(default=apps.requests.models.generate_ticket_number, max_length=50, unique=True, verbose_name='Número de Ticket'),
        ),
    ]
