# Generated by Django 4.2.7 on 2025-09-29 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0003_alter_requeststatushistory_from_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Asignada'), ('ACCEPTED', 'Aceptada'), ('IN_PROGRESS', 'En Progreso'), ('ON_HOLD', 'En Espera'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='ASSIGNED', max_length=20, verbose_name='Estado de la Tarea')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('estimated_completion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('actual_completion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Finalización')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones Especiales')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Técnico')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Estimadas')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Reales')),
                ('materials_needed', models.TextField(blank=True, verbose_name='Materiales Necesarios')),
                ('materials_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Materiales')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='requests.servicerequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Asignada'), ('ACCEPTED', 'Aceptada'), ('IN_PROGRESS', 'En Progreso'), ('ON_HOLD', 'En Espera'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], max_length=20, verbose_name='Estado')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Porcentaje de Progreso')),
                ('description', models.TextField(verbose_name='Descripción del Progreso')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Trabajadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='assignments.taskassignment', verbose_name='Asignación')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Actualización de Tarea',
                'verbose_name_plural': 'Actualizaciones de Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Tarea Asignada'), ('TASK_UPDATED', 'Tarea Actualizada'), ('TASK_COMPLETED', 'Tarea Completada'), ('REQUEST_UPDATED', 'Solicitud Actualizada'), ('GENERAL', 'General')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.servicerequest', verbose_name='Solicitud Relacionada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
