# Generated by Django 4.2.7 on 2025-09-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0003_alter_requeststatushistory_from_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('GENERAL', 'Reporte General'), ('SERVICE_TYPE', 'Por Tipo de Servicio'), ('AREA', 'Por Área'), ('TECHNICIAN', 'Rendimiento de Técnicos'), ('SATISFACTION', 'Satisfacción Ciudadana'), ('MONTHLY', 'Reporte Mensual'), ('ANNUAL', 'Reporte Anual')], max_length=20, verbose_name='Tipo de Reporte')),
                ('date_from', models.DateField(verbose_name='Fecha Desde')),
                ('date_to', models.DateField(verbose_name='Fecha Hasta')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], verbose_name='Calificación')),
                ('response_time_rating', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], verbose_name='Calificación del Tiempo de Respuesta')),
                ('quality_rating', models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], verbose_name='Calificación de la Calidad')),
                ('technician_rating', models.IntegerField(blank=True, choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], null=True, verbose_name='Calificación del Técnico')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='¿Recomendaría el servicio?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='requests.servicerequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Evaluación de Satisfacción',
                'verbose_name_plural': 'Evaluaciones de Satisfacción',
                'ordering': ['-created_at'],
            },
        ),
    ]
